//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicTacToe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Board {
            get {
                object obj = ResourceManager.GetObject("Board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle {
            get {
                object obj = ResourceManager.GetObject("circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circleHighLight {
            get {
                object obj = ResourceManager.GetObject("circleHighLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CorssBarHighLight {
            get {
                object obj = ResourceManager.GetObject("CorssBarHighLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CpuFace {
            get {
                object obj = ResourceManager.GetObject("CpuFace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrossBar {
            get {
                object obj = ResourceManager.GetObject("CrossBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Current {
            get {
                object obj = ResourceManager.GetObject("Current", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap currentCircleHighLight {
            get {
                object obj = ResourceManager.GetObject("currentCircleHighLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap currentCrossBarHighLight {
            get {
                object obj = ResourceManager.GetObject("currentCrossBarHighLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CurrentHighLight {
            get {
                object obj = ResourceManager.GetObject("CurrentHighLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GAMEDRAW {
            get {
                return ResourceManager.GetStream("GAMEDRAW", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GAMEOVER {
            get {
                return ResourceManager.GetStream("GAMEOVER", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PlayerFace {
            get {
                object obj = ResourceManager.GetObject("PlayerFace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScoreBoard {
            get {
                object obj = ResourceManager.GetObject("ScoreBoard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game DRAWED..
        /// </summary>
        internal static string strGameDraw {
            get {
                return ResourceManager.GetString("strGameDraw", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream TIMER {
            get {
                return ResourceManager.GetStream("TIMER", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream VOICE1 {
            get {
                return ResourceManager.GetStream("VOICE1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream VOICE2 {
            get {
                return ResourceManager.GetStream("VOICE2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream VOICE3 {
            get {
                return ResourceManager.GetStream("VOICE3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream VOICE4 {
            get {
                return ResourceManager.GetStream("VOICE4", resourceCulture);
            }
        }
    }
}
