#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezaRestaurant.SQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="RRDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSetting(Setting instance);
    partial void UpdateSetting(Setting instance);
    partial void DeleteSetting(Setting instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void Insertاقلام_فروخته_شده(اقلام_فروخته_شده instance);
    partial void Updateاقلام_فروخته_شده(اقلام_فروخته_شده instance);
    partial void Deleteاقلام_فروخته_شده(اقلام_فروخته_شده instance);
    partial void Insertغذاها(غذاها instance);
    partial void Updateغذاها(غذاها instance);
    partial void Deleteغذاها(غذاها instance);
    partial void Insertفاکتورها(فاکتورها instance);
    partial void Updateفاکتورها(فاکتورها instance);
    partial void Deleteفاکتورها(فاکتورها instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::RezaRestaurant.Properties.Settings.Default.DatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Setting> Settings
		{
			get
			{
				return this.GetTable<Setting>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<اقلام_فروخته_شده> اقلام_فروخته_شدهs
		{
			get
			{
				return this.GetTable<اقلام_فروخته_شده>();
			}
		}
		
		public System.Data.Linq.Table<غذاها> غذاهاs
		{
			get
			{
				return this.GetTable<غذاها>();
			}
		}
		
		public System.Data.Linq.Table<فاکتورها> فاکتورهاs
		{
			get
			{
				return this.GetTable<فاکتورها>();
			}
		}
	}
	
	[Table(Name="dbo.Setting")]
	public partial class Setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    #endregion
		
		public Setting()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_value", DbType="NVarChar(50)")]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_pass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.[اقلام فروخته شده]")]
	public partial class اقلام_فروخته_شده : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _FacotrID;
		
		private string _نام_غذا;
		
		private int _تعداد;
		
		private int _قیمت_یک_واحد;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnFacotrIDChanging(long value);
    partial void OnFacotrIDChanged();
    partial void Onنام_غذاChanging(string value);
    partial void Onنام_غذاChanged();
    partial void OnتعدادChanging(int value);
    partial void OnتعدادChanged();
    partial void Onقیمت_یک_واحدChanging(int value);
    partial void Onقیمت_یک_واحدChanged();
    #endregion
		
		public اقلام_فروخته_شده()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_FacotrID", DbType="BigInt NOT NULL")]
		public long FacotrID
		{
			get
			{
				return this._FacotrID;
			}
			set
			{
				if ((this._FacotrID != value))
				{
					this.OnFacotrIDChanging(value);
					this.SendPropertyChanging();
					this._FacotrID = value;
					this.SendPropertyChanged("FacotrID");
					this.OnFacotrIDChanged();
				}
			}
		}
		
		[Column(Name="[نام غذا]", Storage="_نام_غذا", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string نام_غذا
		{
			get
			{
				return this._نام_غذا;
			}
			set
			{
				if ((this._نام_غذا != value))
				{
					this.Onنام_غذاChanging(value);
					this.SendPropertyChanging();
					this._نام_غذا = value;
					this.SendPropertyChanged("نام_غذا");
					this.Onنام_غذاChanged();
				}
			}
		}
		
		[Column(Storage="_تعداد", DbType="Int NOT NULL")]
		public int تعداد
		{
			get
			{
				return this._تعداد;
			}
			set
			{
				if ((this._تعداد != value))
				{
					this.OnتعدادChanging(value);
					this.SendPropertyChanging();
					this._تعداد = value;
					this.SendPropertyChanged("تعداد");
					this.OnتعدادChanged();
				}
			}
		}
		
		[Column(Name="[قیمت یک واحد]", Storage="_قیمت_یک_واحد", DbType="Int NOT NULL")]
		public int قیمت_یک_واحد
		{
			get
			{
				return this._قیمت_یک_واحد;
			}
			set
			{
				if ((this._قیمت_یک_واحد != value))
				{
					this.Onقیمت_یک_واحدChanging(value);
					this.SendPropertyChanging();
					this._قیمت_یک_واحد = value;
					this.SendPropertyChanged("قیمت_یک_واحد");
					this.Onقیمت_یک_واحدChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.غذاها")]
	public partial class غذاها : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _نام_غذا;
		
		private int _کد_غذا;
		
		private int _قیمت;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onنام_غذاChanging(string value);
    partial void Onنام_غذاChanged();
    partial void Onکد_غذاChanging(int value);
    partial void Onکد_غذاChanged();
    partial void OnقیمتChanging(int value);
    partial void OnقیمتChanged();
    #endregion
		
		public غذاها()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Name="[نام غذا]", Storage="_نام_غذا", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string نام_غذا
		{
			get
			{
				return this._نام_غذا;
			}
			set
			{
				if ((this._نام_غذا != value))
				{
					this.Onنام_غذاChanging(value);
					this.SendPropertyChanging();
					this._نام_غذا = value;
					this.SendPropertyChanged("نام_غذا");
					this.Onنام_غذاChanged();
				}
			}
		}
		
		[Column(Name="[کد غذا]", Storage="_کد_غذا", DbType="Int NOT NULL")]
		public int کد_غذا
		{
			get
			{
				return this._کد_غذا;
			}
			set
			{
				if ((this._کد_غذا != value))
				{
					this.Onکد_غذاChanging(value);
					this.SendPropertyChanging();
					this._کد_غذا = value;
					this.SendPropertyChanged("کد_غذا");
					this.Onکد_غذاChanged();
				}
			}
		}
		
		[Column(Storage="_قیمت", DbType="Int NOT NULL")]
		public int قیمت
		{
			get
			{
				return this._قیمت;
			}
			set
			{
				if ((this._قیمت != value))
				{
					this.OnقیمتChanging(value);
					this.SendPropertyChanging();
					this._قیمت = value;
					this.SendPropertyChanged("قیمت");
					this.OnقیمتChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.فاکتورها")]
	public partial class فاکتورها : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private int _شماره_فاکتور;
		
		private System.Nullable<int> _شماره_میز;
		
		private long _مبلغ_فاکتور;
		
		private string _نوع_فاکتور;
		
		private System.DateTime _تاریخ_ثبت;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void Onشماره_فاکتورChanging(int value);
    partial void Onشماره_فاکتورChanged();
    partial void Onشماره_میزChanging(System.Nullable<int> value);
    partial void Onشماره_میزChanged();
    partial void Onمبلغ_فاکتورChanging(long value);
    partial void Onمبلغ_فاکتورChanged();
    partial void Onنوع_فاکتورChanging(string value);
    partial void Onنوع_فاکتورChanged();
    partial void Onتاریخ_ثبتChanging(System.DateTime value);
    partial void Onتاریخ_ثبتChanged();
    #endregion
		
		public فاکتورها()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Name="[شماره فاکتور]", Storage="_شماره_فاکتور", DbType="Int NOT NULL")]
		public int شماره_فاکتور
		{
			get
			{
				return this._شماره_فاکتور;
			}
			set
			{
				if ((this._شماره_فاکتور != value))
				{
					this.Onشماره_فاکتورChanging(value);
					this.SendPropertyChanging();
					this._شماره_فاکتور = value;
					this.SendPropertyChanged("شماره_فاکتور");
					this.Onشماره_فاکتورChanged();
				}
			}
		}
		
		[Column(Name="[شماره میز]", Storage="_شماره_میز", DbType="Int")]
		public System.Nullable<int> شماره_میز
		{
			get
			{
				return this._شماره_میز;
			}
			set
			{
				if ((this._شماره_میز != value))
				{
					this.Onشماره_میزChanging(value);
					this.SendPropertyChanging();
					this._شماره_میز = value;
					this.SendPropertyChanged("شماره_میز");
					this.Onشماره_میزChanged();
				}
			}
		}
		
		[Column(Name="[مبلغ فاکتور]", Storage="_مبلغ_فاکتور", DbType="BigInt NOT NULL")]
		public long مبلغ_فاکتور
		{
			get
			{
				return this._مبلغ_فاکتور;
			}
			set
			{
				if ((this._مبلغ_فاکتور != value))
				{
					this.Onمبلغ_فاکتورChanging(value);
					this.SendPropertyChanging();
					this._مبلغ_فاکتور = value;
					this.SendPropertyChanged("مبلغ_فاکتور");
					this.Onمبلغ_فاکتورChanged();
				}
			}
		}
		
		[Column(Name="[نوع فاکتور]", Storage="_نوع_فاکتور", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string نوع_فاکتور
		{
			get
			{
				return this._نوع_فاکتور;
			}
			set
			{
				if ((this._نوع_فاکتور != value))
				{
					this.Onنوع_فاکتورChanging(value);
					this.SendPropertyChanging();
					this._نوع_فاکتور = value;
					this.SendPropertyChanged("نوع_فاکتور");
					this.Onنوع_فاکتورChanged();
				}
			}
		}
		
		[Column(Name="[تاریخ ثبت]", Storage="_تاریخ_ثبت", DbType="DateTime NOT NULL")]
		public System.DateTime تاریخ_ثبت
		{
			get
			{
				return this._تاریخ_ثبت;
			}
			set
			{
				if ((this._تاریخ_ثبت != value))
				{
					this.Onتاریخ_ثبتChanging(value);
					this.SendPropertyChanging();
					this._تاریخ_ثبت = value;
					this.SendPropertyChanged("تاریخ_ثبت");
					this.Onتاریخ_ثبتChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
